"use strict";(self.webpackChunkant_design_pro=self.webpackChunkant_design_pro||[]).push([[982],{2803:function(H,b,o){o.r(b),o.d(b,{default:function(){return R}});var h=o(58283),E=o(58357),l=o.n(E),D=o(71977),f=o.n(D),I=o(30577),j=o.n(I),g=o(29956),p=o(79660),v=o(87091),x=o(64224),m=o(60709),A=o(50959),e=o(11527),S=function(){var i=(0,A.useState)(!1),a=j()(i,2),r=a[0],F=a[1];return(0,e.jsx)("div",{style:{margin:-24,padding:24},children:(0,e.jsx)(g.Rs,{pagination:{defaultPageSize:12,showSizeChanger:!1},search:{},showActions:"hover",rowSelection:{},grid:{gutter:16,column:4},onItem:function(u){return{onClick:function(){}}},metas:{title:{dataIndex:"name",title:"\u8BBE\u5907\u540D\u79F0"},subTitle:{dataIndex:"id",title:"\u8BBE\u5907ID",render:function(u,n){return(0,e.jsxs)(v.Z,{color:"cyan",children:["ID:  ",u," "]})}},type:{},avatar:{},content:{render:function(u,n){return(0,e.jsxs)("div",{style:{flex:1},children:[(0,e.jsx)("img",{src:n==null?void 0:n.image,alt:"\u5361\u7247\u56FE\u7247"}),(0,e.jsx)("div",{children:"\u751F\u547D\u5C31\u50CF\u4E00\u76D2\u5DE7\u514B\u529B\uFF0C\u7ED3\u679C\u5F80\u5F80\u51FA\u4EBA\u610F\u6599"})]})}},actions:{render:function(u,n){return[(0,e.jsx)(x.Z,{title:(0,e.jsx)("span",{dangerouslySetInnerHTML:{__html:"\u54C1\u724C\uFF1A".concat(n.brand,`<br />
                          \u4EAE\u5EA6\uFF1A`).concat(n.brightness,`%<br />
                          \u7535\u91CF\uFF1A`).concat(n.power,`%<br />
                          \u5F53\u524D\u72B6\u6001\uFF1A`).concat(n.isOn?"\u5F00\u542F":"\u5173\u95ED",`<br />
                          \u662F\u5426\u5B9A\u65F6\uFF1A`).concat(n.isTimerOn?"\u662F":"\u5426","<br />")}}),children:(0,e.jsx)("a",{children:"\u8BE6\u60C5"},"detail")},"detail"),(0,e.jsx)("a",{children:(0,e.jsx)(m.Z,{defaultChecked:n.isOn})},"delete")]},cardActionProps:"actions"}},request:function(){var t=f()(l()().mark(function u(n){var d,c;return l()().wrap(function(s){for(;;)switch(s.prev=s.next){case 0:return s.next=2,(0,p.request)("/api/devices");case 2:return d=s.sent,c=d.airConditioners,console.log(c),s.abrupt("return",{data:c,total:c.length});case 6:case"end":return s.stop()}},u)}));return function(u){return t.apply(this,arguments)}}()})})},y=function(){var i=(0,A.useState)(!1),a=j()(i,2),r=a[0],F=a[1];return(0,e.jsx)("div",{style:{margin:-24,padding:24},children:(0,e.jsx)(g.Rs,{pagination:{defaultPageSize:12,showSizeChanger:!1},search:{},showActions:"hover",rowSelection:{},grid:{gutter:16,column:4},onItem:function(u){return{onClick:function(){}}},metas:{title:{dataIndex:"name",title:"\u8BBE\u5907\u540D\u79F0"},subTitle:{dataIndex:"id",title:"\u8BBE\u5907ID",render:function(u,n){return(0,e.jsxs)(v.Z,{color:"cyan",children:["ID:  ",u," "]})}},type:{},avatar:{},content:{render:function(u,n){return(0,e.jsxs)("div",{style:{flex:1},children:[(0,e.jsx)("img",{src:n==null?void 0:n.image,alt:"\u5361\u7247\u56FE\u7247"}),(0,e.jsx)("div",{children:"\u751F\u547D\u5C31\u50CF\u4E00\u76D2\u5DE7\u514B\u529B\uFF0C\u7ED3\u679C\u5F80\u5F80\u51FA\u4EBA\u610F\u6599"})]})}},actions:{render:function(u,n){return[(0,e.jsx)(x.Z,{title:(0,e.jsx)("span",{dangerouslySetInnerHTML:{__html:"\u54C1\u724C\uFF1A".concat(n.brand,`<br />
                          \u4EAE\u5EA6\uFF1A`).concat(n.brightness,`%<br />
                          \u7535\u91CF\uFF1A`).concat(n.power,`%<br />
                          \u5F53\u524D\u72B6\u6001\uFF1A`).concat(n.isOn?"\u5F00\u542F":"\u5173\u95ED",`<br />
                          \u662F\u5426\u5B9A\u65F6\uFF1A`).concat(n.isTimerOn?"\u662F":"\u5426","<br />")}}),children:(0,e.jsx)("a",{children:"\u8BE6\u60C5"},"detail")},"detail"),(0,e.jsx)("a",{children:(0,e.jsx)(m.Z,{defaultChecked:n.isOn})},"delete")]},cardActionProps:"actions"}},request:function(){var t=f()(l()().mark(function u(n){var d,c;return l()().wrap(function(s){for(;;)switch(s.prev=s.next){case 0:return s.next=2,(0,p.request)("/api/devices");case 2:return d=s.sent,c=d.cleaningRobots,console.log(c),s.abrupt("return",{data:c,total:c.length});case 6:case"end":return s.stop()}},u)}));return function(u){return t.apply(this,arguments)}}()})})},B=function(){return(0,e.jsx)("div",{style:{margin:-24,padding:24},children:(0,e.jsx)(g.Rs,{pagination:{defaultPageSize:12,showSizeChanger:!1},search:{},showActions:"hover",rowSelection:{},grid:{gutter:16,column:4},onItem:function(a){return{onClick:function(){}}},metas:{title:{dataIndex:"name",title:"\u8BBE\u5907\u540D\u79F0"},subTitle:{dataIndex:"id",title:"\u8BBE\u5907ID",render:function(a,r){return(0,e.jsxs)(v.Z,{color:"cyan",children:["ID:  ",a," "]})}},type:{},avatar:{},content:{render:function(a,r){return(0,e.jsxs)("div",{style:{flex:1},children:[(0,e.jsx)("img",{src:r==null?void 0:r.image,alt:"\u5361\u7247\u56FE\u7247"}),(0,e.jsx)("div",{children:"\u751F\u547D\u5C31\u50CF\u4E00\u76D2\u5DE7\u514B\u529B\uFF0C\u7ED3\u679C\u5F80\u5F80\u51FA\u4EBA\u610F\u6599"})]})}},actions:{render:function(a,r){return[(0,e.jsx)(x.Z,{title:(0,e.jsx)("span",{dangerouslySetInnerHTML:{__html:"\u54C1\u724C\uFF1A".concat(r.brand,`<br />
                          \u4EAE\u5EA6\uFF1A`).concat(r.brightness,`%<br />
                          \u7535\u91CF\uFF1A`).concat(r.power,`%<br />
                          \u5F53\u524D\u72B6\u6001\uFF1A`).concat(r.isOn?"\u5F00\u542F":"\u5173\u95ED",`<br />
                          \u662F\u5426\u5B9A\u65F6\uFF1A`).concat(r.isTimerOn?"\u662F":"\u5426","<br />")}}),children:(0,e.jsx)("a",{children:"\u8BE6\u60C5"},"detail")},"detail"),(0,e.jsx)("a",{children:(0,e.jsx)(m.Z,{defaultChecked:r.isOn})},"delete")]},cardActionProps:"actions"}},request:function(){var i=f()(l()().mark(function a(r){var F,t;return l()().wrap(function(n){for(;;)switch(n.prev=n.next){case 0:return n.next=2,(0,p.request)("/api/devices");case 2:return F=n.sent,t=F.curtains,console.log(t),n.abrupt("return",{data:t,total:t.length});case 6:case"end":return n.stop()}},a)}));return function(a){return i.apply(this,arguments)}}()})})},T=function(){var i=(0,A.useState)(!1),a=j()(i,2),r=a[0],F=a[1];return(0,e.jsx)("div",{style:{margin:-24,padding:24},children:(0,e.jsx)(g.Rs,{pagination:{defaultPageSize:12,showSizeChanger:!1},search:{},showActions:"hover",rowSelection:{},grid:{gutter:16,column:4},onItem:function(u){return{onClick:function(){}}},metas:{title:{dataIndex:"name",title:"\u8BBE\u5907\u540D\u79F0"},subTitle:{dataIndex:"id",title:"\u8BBE\u5907ID",render:function(u,n){return(0,e.jsxs)(v.Z,{color:"cyan",children:["ID:  ",u," "]})}},type:{},avatar:{},content:{render:function(u,n){return(0,e.jsxs)("div",{style:{flex:1},children:[(0,e.jsx)("img",{src:n==null?void 0:n.image,alt:"\u5361\u7247\u56FE\u7247"}),(0,e.jsx)("div",{children:"\u751F\u547D\u5C31\u50CF\u4E00\u76D2\u5DE7\u514B\u529B\uFF0C\u7ED3\u679C\u5F80\u5F80\u51FA\u4EBA\u610F\u6599"})]})}},actions:{render:function(u,n){return[(0,e.jsx)(x.Z,{title:(0,e.jsx)("span",{dangerouslySetInnerHTML:{__html:"\u54C1\u724C\uFF1A".concat(n.brand,`<br />
                          \u4EAE\u5EA6\uFF1A`).concat(n.brightness,`%<br />
                          \u7535\u91CF\uFF1A`).concat(n.power,`%<br />
                          \u5F53\u524D\u72B6\u6001\uFF1A`).concat(n.isOn?"\u5F00\u542F":"\u5173\u95ED",`<br />
                          \u662F\u5426\u5B9A\u65F6\uFF1A`).concat(n.isTimerOn?"\u662F":"\u5426","<br />")}}),children:(0,e.jsx)("a",{children:"\u8BE6\u60C5"},"detail")},"detail"),(0,e.jsx)("a",{children:(0,e.jsx)(m.Z,{defaultChecked:n.isOn})},"delete")]},cardActionProps:"actions"}},request:function(){var t=f()(l()().mark(function u(n){var d,c;return l()().wrap(function(s){for(;;)switch(s.prev=s.next){case 0:return s.next=2,(0,p.request)("/api/devices");case 2:return d=s.sent,c=d.lights,console.log(c),s.abrupt("return",{data:c,total:c.length});case 6:case"end":return s.stop()}},u)}));return function(u){return t.apply(this,arguments)}}()})})},Z=function(){var i=(0,A.useState)(!1),a=j()(i,2),r=a[0],F=a[1];return(0,e.jsx)("div",{style:{margin:-24,padding:24},children:(0,e.jsx)(g.Rs,{pagination:{defaultPageSize:12,showSizeChanger:!1},search:{},showActions:"hover",rowSelection:{},grid:{gutter:16,column:4},onItem:function(u){return{onClick:function(){}}},metas:{title:{dataIndex:"name",title:"\u8BBE\u5907\u540D\u79F0"},subTitle:{dataIndex:"id",title:"\u8BBE\u5907ID",render:function(u,n){return(0,e.jsxs)(v.Z,{color:"cyan",children:["ID:  ",u," "]})}},type:{},avatar:{},content:{render:function(u,n){return(0,e.jsxs)("div",{style:{flex:1},children:[(0,e.jsx)("img",{src:n==null?void 0:n.image,alt:"\u5361\u7247\u56FE\u7247"}),(0,e.jsx)("div",{children:"\u751F\u547D\u5C31\u50CF\u4E00\u76D2\u5DE7\u514B\u529B\uFF0C\u7ED3\u679C\u5F80\u5F80\u51FA\u4EBA\u610F\u6599"})]})}},actions:{render:function(u,n){return[(0,e.jsx)(x.Z,{title:(0,e.jsx)("span",{dangerouslySetInnerHTML:{__html:"\u54C1\u724C\uFF1A".concat(n.brand,`<br />
                          \u4EAE\u5EA6\uFF1A`).concat(n.brightness,`%<br />
                          \u7535\u91CF\uFF1A`).concat(n.power,`%<br />
                          \u5F53\u524D\u72B6\u6001\uFF1A`).concat(n.isOn?"\u5F00\u542F":"\u5173\u95ED",`<br />
                          \u662F\u5426\u5B9A\u65F6\uFF1A`).concat(n.isTimerOn?"\u662F":"\u5426","<br />")}}),children:(0,e.jsx)("a",{children:"\u8BE6\u60C5"},"detail")},"detail"),(0,e.jsx)("a",{children:(0,e.jsx)(m.Z,{defaultChecked:n.isOn})},"delete")]},cardActionProps:"actions"}},request:function(){var t=f()(l()().mark(function u(n){var d,c;return l()().wrap(function(s){for(;;)switch(s.prev=s.next){case 0:return s.next=2,(0,p.request)("/api/devices");case 2:return d=s.sent,c=d.locks,console.log(c),s.abrupt("return",{data:c,total:c.length});case 6:case"end":return s.stop()}},u)}));return function(u){return t.apply(this,arguments)}}()})})},k=function(){return(0,e.jsx)("div",{style:{margin:-24,padding:24},children:(0,e.jsx)(g.Rs,{pagination:{defaultPageSize:12,showSizeChanger:!1},search:{},showActions:"hover",rowSelection:{},grid:{gutter:16,column:4},onItem:function(a){return{onClick:function(){}}},metas:{title:{dataIndex:"name",title:"\u8BBE\u5907\u540D\u79F0"},subTitle:{dataIndex:"id",title:"\u8BBE\u5907ID",render:function(a,r){return(0,e.jsxs)(v.Z,{color:"cyan",children:["ID:  ",a," "]})}},type:{},avatar:{},content:{render:function(a,r){return(0,e.jsxs)("div",{style:{flex:1},children:[(0,e.jsx)("img",{src:r==null?void 0:r.image,alt:"\u5361\u7247\u56FE\u7247"}),(0,e.jsx)("div",{children:"\u751F\u547D\u5C31\u50CF\u4E00\u76D2\u5DE7\u514B\u529B\uFF0C\u7ED3\u679C\u5F80\u5F80\u51FA\u4EBA\u610F\u6599"})]})}},actions:{render:function(a,r){return[(0,e.jsx)(x.Z,{title:(0,e.jsx)("span",{dangerouslySetInnerHTML:{__html:"\u54C1\u724C\uFF1A".concat(r.brand,`<br />
                          \u4EAE\u5EA6\uFF1A`).concat(r.brightness,`%<br />
                          \u7535\u91CF\uFF1A`).concat(r.power,`%<br />
                          \u5F53\u524D\u72B6\u6001\uFF1A`).concat(r.isOn?"\u5F00\u542F":"\u5173\u95ED",`<br />
                          \u662F\u5426\u5B9A\u65F6\uFF1A`).concat(r.isTimerOn?"\u662F":"\u5426","<br />")}}),children:(0,e.jsx)("a",{children:"\u8BE6\u60C5"},"detail")},"detail"),(0,e.jsx)("a",{children:(0,e.jsx)(m.Z,{defaultChecked:r.isOn})},"delete")]},cardActionProps:"actions"}},request:function(){var i=f()(l()().mark(function a(r){var F,t;return l()().wrap(function(n){for(;;)switch(n.prev=n.next){case 0:return n.next=2,(0,p.request)("/api/devices");case 2:return F=n.sent,t=F.refrigerators,console.log(t),n.abrupt("return",{data:t,total:t.length});case 6:case"end":return n.stop()}},a)}));return function(a){return i.apply(this,arguments)}}()})})},P=function(){return(0,e.jsx)("div",{style:{margin:-24,padding:24},children:(0,e.jsx)(g.Rs,{pagination:{defaultPageSize:12,showSizeChanger:!1},search:{},showActions:"hover",rowSelection:{},grid:{gutter:16,column:4},onItem:function(a){return{onClick:function(){}}},metas:{title:{dataIndex:"name",title:"\u8BBE\u5907\u540D\u79F0"},subTitle:{dataIndex:"id",title:"\u8BBE\u5907ID",render:function(a,r){return(0,e.jsxs)(v.Z,{color:"cyan",children:["ID:  ",a," "]})}},type:{},avatar:{},content:{render:function(a,r){return(0,e.jsxs)("div",{style:{flex:1},children:[(0,e.jsx)("img",{src:r==null?void 0:r.image,alt:"\u5361\u7247\u56FE\u7247"}),(0,e.jsx)("div",{children:"\u751F\u547D\u5C31\u50CF\u4E00\u76D2\u5DE7\u514B\u529B\uFF0C\u7ED3\u679C\u5F80\u5F80\u51FA\u4EBA\u610F\u6599"})]})}},actions:{render:function(a,r){return[(0,e.jsx)(x.Z,{title:(0,e.jsx)("span",{dangerouslySetInnerHTML:{__html:"\u54C1\u724C\uFF1A".concat(r.brand,`<br />
                          \u4EAE\u5EA6\uFF1A`).concat(r.brightness,`%<br />
                          \u7535\u91CF\uFF1A`).concat(r.power,`%<br />
                          \u5F53\u524D\u72B6\u6001\uFF1A`).concat(r.isOn?"\u5F00\u542F":"\u5173\u95ED",`<br />
                          \u662F\u5426\u5B9A\u65F6\uFF1A`).concat(r.isTimerOn?"\u662F":"\u5426","<br />")}}),children:(0,e.jsx)("a",{children:"\u8BE6\u60C5"},"detail")},"detail"),(0,e.jsx)("a",{children:(0,e.jsx)(m.Z,{defaultChecked:r.isOn})},"delete")]},cardActionProps:"actions"}},request:function(){var i=f()(l()().mark(function a(r){var F,t;return l()().wrap(function(n){for(;;)switch(n.prev=n.next){case 0:return n.next=2,(0,p.request)("/api/devices");case 2:return F=n.sent,t=F.sockets,console.log(t),n.abrupt("return",{data:t,total:t.length});case 6:case"end":return n.stop()}},a)}));return function(a){return i.apply(this,arguments)}}()})})},O=function(){var i=(0,A.useState)(!1),a=j()(i,2),r=a[0],F=a[1];return(0,e.jsx)("div",{style:{margin:-24,padding:24},children:(0,e.jsx)(g.Rs,{pagination:{defaultPageSize:12,showSizeChanger:!1},search:{},showActions:"hover",rowSelection:{},grid:{gutter:16,column:4},onItem:function(u){return{onClick:function(){}}},metas:{title:{dataIndex:"name",title:"\u8BBE\u5907\u540D\u79F0"},subTitle:{dataIndex:"id",title:"\u8BBE\u5907ID",render:function(u,n){return(0,e.jsxs)(v.Z,{color:"cyan",children:["ID:  ",u," "]})}},type:{},avatar:{},content:{render:function(u,n){return(0,e.jsxs)("div",{style:{flex:1},children:[(0,e.jsx)("img",{src:n==null?void 0:n.image,alt:"\u5361\u7247\u56FE\u7247"}),(0,e.jsx)("div",{children:"\u751F\u547D\u5C31\u50CF\u4E00\u76D2\u5DE7\u514B\u529B\uFF0C\u7ED3\u679C\u5F80\u5F80\u51FA\u4EBA\u610F\u6599"})]})}},actions:{render:function(u,n){return[(0,e.jsx)(x.Z,{title:(0,e.jsx)("span",{dangerouslySetInnerHTML:{__html:"\u54C1\u724C\uFF1A".concat(n.brand,`<br />
                          \u4EAE\u5EA6\uFF1A`).concat(n.brightness,`%<br />
                          \u7535\u91CF\uFF1A`).concat(n.power,`%<br />
                          \u5F53\u524D\u72B6\u6001\uFF1A`).concat(n.isOn?"\u5F00\u542F":"\u5173\u95ED",`<br />
                          \u662F\u5426\u5B9A\u65F6\uFF1A`).concat(n.isTimerOn?"\u662F":"\u5426","<br />")}}),children:(0,e.jsx)("a",{children:"\u8BE6\u60C5"},"detail")},"detail"),(0,e.jsx)("a",{children:(0,e.jsx)(m.Z,{defaultChecked:n.isOn})},"delete")]},cardActionProps:"actions"}},request:function(){var t=f()(l()().mark(function u(n){var d,c;return l()().wrap(function(s){for(;;)switch(s.prev=s.next){case 0:return s.next=2,(0,p.request)("/api/devices");case 2:return d=s.sent,c=d.speakers,console.log(c),s.abrupt("return",{data:c,total:c.length});case 6:case"end":return s.stop()}},u)}));return function(u){return t.apply(this,arguments)}}()})})},z=function(){var i=(0,A.useState)(!1),a=j()(i,2),r=a[0],F=a[1];return(0,e.jsx)("div",{style:{margin:-24,padding:24},children:(0,e.jsx)(g.Rs,{pagination:{defaultPageSize:12,showSizeChanger:!1},search:{},showActions:"hover",rowSelection:{},grid:{gutter:16,column:4},onItem:function(u){return{onClick:function(){}}},metas:{title:{dataIndex:"name",title:"\u8BBE\u5907\u540D\u79F0"},subTitle:{dataIndex:"id",title:"\u8BBE\u5907ID",render:function(u,n){return(0,e.jsxs)(v.Z,{color:"cyan",children:["ID:  ",u," "]})}},type:{},avatar:{},content:{render:function(u,n){return(0,e.jsxs)("div",{style:{flex:1},children:[(0,e.jsx)("img",{src:n==null?void 0:n.image,alt:"\u5361\u7247\u56FE\u7247"}),(0,e.jsx)("div",{children:"\u751F\u547D\u5C31\u50CF\u4E00\u76D2\u5DE7\u514B\u529B\uFF0C\u7ED3\u679C\u5F80\u5F80\u51FA\u4EBA\u610F\u6599"})]})}},actions:{render:function(u,n){return[(0,e.jsx)(x.Z,{title:(0,e.jsx)("span",{dangerouslySetInnerHTML:{__html:"\u54C1\u724C\uFF1A".concat(n.brand,`<br />
                          \u4EAE\u5EA6\uFF1A`).concat(n.brightness,`%<br />
                          \u7535\u91CF\uFF1A`).concat(n.power,`%<br />
                          \u5F53\u524D\u72B6\u6001\uFF1A`).concat(n.isOn?"\u5F00\u542F":"\u5173\u95ED",`<br />
                          \u662F\u5426\u5B9A\u65F6\uFF1A`).concat(n.isTimerOn?"\u662F":"\u5426","<br />")}}),children:(0,e.jsx)("a",{children:"\u8BE6\u60C5"},"detail")},"detail"),(0,e.jsx)("a",{children:(0,e.jsx)(m.Z,{defaultChecked:n.isOn})},"delete")]},cardActionProps:"actions"}},request:function(){var t=f()(l()().mark(function u(n){var d,c;return l()().wrap(function(s){for(;;)switch(s.prev=s.next){case 0:return s.next=2,(0,p.request)("/api/devices");case 2:return d=s.sent,c=d.TVs,console.log(c),s.abrupt("return",{data:c,total:c.length});case 6:case"end":return s.stop()}},u)}));return function(u){return t.apply(this,arguments)}}()})})},R=function(){return(0,e.jsxs)(h.Z,{tabs:{type:"card"},children:[(0,e.jsx)(h.Z.TabPane,{tab:"\u706F\u5177",children:(0,e.jsx)(T,{})},"tab1"),(0,e.jsx)(h.Z.TabPane,{tab:"\u63D2\u5EA7",children:(0,e.jsx)(P,{})},"tab2"),(0,e.jsx)(h.Z.TabPane,{tab:"\u7A97\u5E18",children:(0,e.jsx)(B,{})},"tab3"),(0,e.jsx)(h.Z.TabPane,{tab:"\u51B0\u7BB1",children:(0,e.jsx)(k,{})},"tab4"),(0,e.jsx)(h.Z.TabPane,{tab:"\u95E8\u9501",children:(0,e.jsx)(Z,{})},"tab5"),(0,e.jsx)(h.Z.TabPane,{tab:"\u7535\u89C6",children:(0,e.jsx)(z,{})},"tab6"),(0,e.jsx)(h.Z.TabPane,{tab:"\u97F3\u54CD",children:(0,e.jsx)(O,{})},"tab7"),(0,e.jsx)(h.Z.TabPane,{tab:"\u626B\u5730\u673A\u5668\u4EBA",children:(0,e.jsx)(y,{})},"tab8"),(0,e.jsx)(h.Z.TabPane,{tab:"\u7A7A\u8C03",children:(0,e.jsx)(S,{})},"tab9")]})}}}]);
