// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { defineApp } from './core/defineApp'
export type { RuntimeConfig } from './core/defineApp'
// @umijs/renderer-*
export { createBrowserHistory, createHashHistory, createMemoryHistory, createSearchParams, generatePath, matchPath, matchRoutes, Navigate, NavLink, Outlet, resolvePath, useLocation, useMatch, useNavigate, useOutlet, useOutletContext, useParams, useResolvedPath, useRoutes, useSearchParams, Helmet, useAppData, useSelectedRoutes, useClientLoaderData, useServerLoaderData, renderClient, __getRoot, Link, useRouteData, __useFetcher, withRouter } from 'D:/Microsoft VS Code/code/smart-appliance-admin/node_modules/.pnpm/@umijs+renderer-react@4.0.52_react-dom@18.1.0_react@18.1.0/node_modules/@umijs/renderer-react';
export type {  History } from 'D:/Microsoft VS Code/code/smart-appliance-admin/node_modules/.pnpm/@umijs+renderer-react@4.0.52_react-dom@18.1.0_react@18.1.0/node_modules/@umijs/renderer-react'
// umi/client/client/plugin
export { ApplyPluginsType, PluginManager } from 'D:/Microsoft VS Code/code/smart-appliance-admin/node_modules/.pnpm/umi@4.0.52_@babel+core@7.20.12_@types+node@18.14.0_@types+react@18.0.28_eslint@8.31.0_jest@29_rsroai5kcf4tqa3mr6dnetczj4/node_modules/umi/client/client/plugin.js';
export { history, createHistory } from './core/history';
export { terminal } from './core/terminal';
export { TestBrowser } from './testBrowser';
// plugins
export { Access, useAccess, useAccessMarkedRoutes } from 'D:/Microsoft VS Code/code/smart-appliance-admin/src/.umi/plugin-access';
export { addLocale, setLocale, getLocale, getIntl, useIntl, injectIntl, formatMessage, FormattedMessage, getAllLocales, FormattedDate, FormattedDateParts, FormattedDisplayName, FormattedHTMLMessage, FormattedList, FormattedNumber, FormattedNumberParts, FormattedPlural, FormattedRelativeTime, FormattedTime, FormattedTimeParts, IntlProvider, RawIntlProvider, SelectLang } from 'D:/Microsoft VS Code/code/smart-appliance-admin/src/.umi/plugin-locale';
export { Provider, useModel } from 'D:/Microsoft VS Code/code/smart-appliance-admin/src/.umi/plugin-model';
export { useRequest, UseRequestProvider, request, getRequestInstance } from 'D:/Microsoft VS Code/code/smart-appliance-admin/src/.umi/plugin-request';
// plugins types.d.ts
export * from 'D:/Microsoft VS Code/code/smart-appliance-admin/src/.umi/plugin-access/types.d';
export * from 'D:/Microsoft VS Code/code/smart-appliance-admin/src/.umi/plugin-layout/types.d';
export * from 'D:/Microsoft VS Code/code/smart-appliance-admin/src/.umi/plugin-request/types.d';
